# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: MandelbrotApp
  name: MandelbrotApp
spec:
  containers:
  - image: docker.io/lucchoubert/mandelbrotbackend:latest
    name: backend
    ports:
    - containerPort: 80
      hostPort: 80
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/lucchoubert/mandelbrotfrontend:latest
    name: frontend
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Never
status: {}

