#cloud-config

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINPyKAZRxltPF8fj5xIKfzMAmnxjFWYnQUmSSQcSfSk0 luc@Luc-Ubuntu
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXUqCZQxSfaxfuCX+Ab4be6k8ZvzCkgLwAo8ohJjUYJ

package_upgrade: true

packages:
  - vim
  - podman

runcmd:
  - [sh, -xc, "chmod o+rw /run/podman/podman.sock" ]

final_message: "The system is finally up, after $UPTIME seconds"
